### ISSUE TITLE
EuBIC 2020 developer’s meeting

### ISSUE THREAD

**Issue by tobiasko** [rformassspectrometry/RforMassSpectrometry#15]
Hi R for MS developers,

not sure if you are aware of this:

```
We are pleased to announce that the upcoming EuBIC 2020 developer’s meeting will be held in Nyborg, Denmark, on January 13th to 17th 2020.

The EuBIC 2020 developer's meeting will bring together scientists active in the field of bioinformatics and computational proteomics. It provides a highly interactive platform to develop projects that are relevant to the proteomics community.

Date: January 13-17, 2020
Venue: Sinatur Hotel Storebælt, Østerøvej 121, 5800 Nyborg, Denmark
Website: https://www.proteomics-academy.org/eubic-dev-meeting-2020


Key dates

September 18, 2019: Project proposal submission deadline
October 1, 2019: Announcement of selected projects
October 1, 2019: Conference registration opens
January 13-17, 2020: EuBIC 2020 developer's meeting in Nyborg


Call for project proposals

Do you want other researchers working on your project and set up future collaborations?  The call for topics for the hackathon sessions during the EuBIC 2020 developer's meeting is now open!

During the EuBIC 2020 developer’s meeting the participants will engage in hackathon sessions where they will develop bioinformatics tools and resources. The participants will break up into small groups to work together on these topics in an open, constructive, and productive atmosphere.

You can now submit project proposals for inclusion into the EuBIC 2020 developer’s meeting program. Submit your project proposal before 18 September through the following website: https://github.com/eubic/EuBIC2020

5-8 hackathon projects will be selected by a community vote arranged by the EuBIC program committee and announced on the conference webpage.


Topics

Hackathon projects can cover all topics in computational mass spectrometry and proteomics bioinformatics, including, but not limited to:

- Tools
    - Extension of existing bioinformatics tools under the guidance of their original authors
    - Development of novel bioinformatics tools to solve open problems

- Benchmarking
    - Compilation of gold-truth datasets
    - Collection of reference algorithmic implementations
    - Specification of benchmarking criteria

- Workflows
    - Definition of formal protocols
    - Development of tutorials for bioinformatics software usage

- Data analysis
    - (Re)analysis of publicly available proteomics datasets
    - Functional data analysis and integration


More information

- Website: https://github.com/eubic/EuBIC2020
- Social media hashtag: #EuBIC20
- Conference email: eubic2020@rub.de


Sponsorship inquiries are welcome at eubic2020@rub.de

We are grateful to the European Proteomics Association (EuPA) for supporting EuBIC and to the Novo Nordisk Foundation for their generous support of the conference! 


We look forward to welcoming you in Nyborg!

The organizing committee.

Veit Schwämmle
Marie Locard-Paulet
Wout Bittremieux
David Bouyssié
Viktoria Dorfer
Dominik Kopczynski
Alessio Soggiu
Julian Uszkoreit
Bart Van Puyvelde
Sander Willems
```

CP & me were wondering: Would it make sense to submit a project proposal that aims at developing a computational framework for trapped ion mobility spectrometry (TIMS) in R?

Michelmann, K., Silveira, J. A., Ridgeway, M. E., & Park, M. A. (2015). Fundamentals of trapped ion mobility spectrometry. Journal of the American Society for Mass Spectrometry, 26(1), 14–24. http://doi.org/10.1007/s13361-014-0999-4

This could boil down to a MSbackend that can read Bruker tdf formated data. This data is novel in the sense that it contains an additional dimension (4D) compared to LC-MS data recorded on qTOFs or qOrbi instruments. Therefore, I expect a lot of challenges for visualisation and analysis. The tfd format is also unique with respect to its internal structure, since all metadata is stored in a SQLite DB, while the peak lists sit in a binary container that can be queried using an API. PASEF data recorded on the timsTOF Pro is stored like this.

What do you think? Would any of you be willing to go there and drive such a project?

Greetings,
Tobi

**Comment by lgatto** [comment]
Thank you for the suggestion. We had similar thoughts (although not specifically for TIMS).
But before that, there's also the EuroBioc 2019 meeting in Belgium, where we also intend to meet and work.
I think it boilds down to traveling and organisation. No hard plans on our side yet.

**Comment by cpanse** [comment]
Of course, we are going to submit an abstract (MsBackendRawFilereader) to EuroBioc 2019. The registration page is not available yet. Right?

**Comment by lgatto** [comment]
Not yet. Probably needs another 2 to 3 weeks.

**Comment by tobiasko** [comment]
Hi again,

are you interested to meet at the bioc2019 in the framework of the User/developer sessions? So far no `Group:` [issues](https://github.com/Bioconductor/EuroBioc2019/issues)

Greetings,
Tobi

**Comment by lgatto** [comment]
Yes, of course - I will be creating an issue for a MS/proteomics/metabolomics session in the coming days.

**Comment by cpanse** [comment]
I wonder if we could focus our discussion on R for MS-related issues only (Spectra/Chromatogram packages and their exiting and future MsBackends).
 I am a bit afraid of going too broad and finally wasting time.

**Comment by lgatto** [comment]
Sure - to be discussed in the coming issue. There could also be sub-groups, depending on number of participants.

**Comment by tobiasko** [comment]
A related question: Will anyone of you present at [EuBIC developers meeting](https://eubic-ms.org/events/2020-developers-meeting/) ???

**Comment by jorainer** [comment]
I plan to - given that my talk will be accepted...
