### ISSUE TITLE
RforMassSpectrometry contributions

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/RforMassSpectrometry#2]
Document external contributions SOP, requirements for contributor/co-athor status.

**Comment by jorainer** [comment]
I would call the following contributions as *substantial*:
- new functionality that goes beyond e.g. a simple plot function
- bug fix combined with related unit test
- extended documentation, examples or vignette describing a complete (potentially alternative) analysis workflow

What is not a substantial contribution *per-se*:
- fix typo(s)

**Comment by lgatto** [comment]
See the [new vignette](https://github.com/rformassspectrometry/RforMassSpectrometry/blob/dc9c2f561375adff951f6dfb7e4023b0a9ad60a4/vignettes/RforMassSpectrometry.Rmd#L62-L101).
If you are happy with this, I'll build the package webpage.

**Comment by jorainer** [comment]
OK from my side! Great! Thanks!

**Comment by sgibb** [comment]
Fine. I think that is very clear. For some more technical details: e.g. how to code, how to make a PR, we could maybe use the following for inspiration:
- https://github.com/tidyverse/.github/blob/master/CONTRIBUTING.md
- https://github.com/MycroftAI/mycroft-core/blob/dev/.github/CONTRIBUTING.md

**Comment by lgatto** [comment]
Thanks, links added until we produce our own more extensive instructions.
