### ISSUE TITLE
e-mail address for maintainer

### ISSUE THREAD

**Issue by sgibb** [rformassspectrometry/RforMassSpectrometry#21]
It would be nice to have a common/shared e-mail address for the maintainer field in `DESCRIPTION`.

**Comment by lgatto** [comment]
> Dear Johannes and Sebastian, 
>
> If you read this email, it means that I finally managed to set up email forwarding for maintainer@rformassspectrometry.org and the three of us should have received it. If so, please say so in issue 21. 
>
> Best wishes,
> Laurent

**Comment by sgibb** [comment]
Got it, thanks.

**Comment by jorainer** [comment]
Me too.
