### ISSUE TITLE
Have a repository for workshops?

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/RforMassSpectrometry#24]
Based on the discussion with @stanstrup and @cbroeckl [here](https://github.com/sneumann/xcms/issues/451#issuecomment-595698954) I was wondering whether it would not be nice to have a repository with some workshops and tutorials here?

Maybe with some sub-folders *a-la*
workshops/metabolomics
workshops/proteomics
...

I would have already a workshop describing `xcms` pre-processing which I could move... Other workshops could then also focus on the new functionality of `Spectra`...

@lgatto @sgibb any thoughts?

**Comment by lgatto** [comment]
I am not keen on something like that. I think we need coordinated material for the project (call it workflow, book, tutorials,...) but we can't start collecting too dispersed repos. However, we could have a file with links and descriptions of related or useful material. That would be a great thing.

**Comment by stanstrup** [comment]
The main problem I saw is that a lot of useful scripts are found in github issues and people will never find them there. If that kind of thing could be collected somewhere it would be a real treasure.

**Comment by lgatto** [comment]
We acknowledge the need for a better centralised documentation, of a least a single page with links to useful documentation. The [book](https://rformassspectrometry.github.io/book/) is one attempt.
