### ISSUE TITLE
RforMassSpectrometry development call - 27 August 2020, 8:30

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/RforMassSpectrometry#27]
- Submission of `Spectra` to Bioconductor (@lgatto or @jorainer, whoever finds time first). Any other packages? (Later, backend packages) `QFeatures` was recently accepted 
- News on `MsFeatures`: to be discussed in a dedicated call with other participants
- Modularise retention time alignment methods for wider reuse.
- What about using the #proteomics and #massspec channels on the Bioc slack? Consider creating a #massspec channel.

**Comment by jorainer** [comment]
- [Abstract](https://github.com/jorainer/metabolomics2020) submitted to [metabolomics 2020](http://www.metabolomics2020.org/)
- Updates/discussion on C-implementation of functions in `MsCoreUtils`.
- *metaRbolomics* hackathon organized by Steffen Neumann beginning 2021 (not clear if will happen thoug - will update once there is more information).
