### ISSUE TITLE
Name for *core* package

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/RforMassSpectrometry#3]
Potential names for the *core* Mass spec package:
1) `MassSpecCore`
2) `MassSpecUtils`
3) `MassSpecTools`

Instead of `MassSpec` we could also use `Ms`, but somehow I started liking the longer, but more explanatory names. 

Note also that there are already plenty of `mass spec utils` softwares around.

**Comment by lgatto** [comment]
My vote would be for `MassSpecUtils` (or `MsUtils`). My least preferred suggestion is by far `*Tools`.

**Comment by jorainer** [comment]
Regarding sticker:
`MassSpecCore`
<img width="733" alt="WCM0104" src="https://user-images.githubusercontent.com/5506112/61279819-21d56e00-a7b7-11e9-95cb-2736c80fe4a5.png">

`MassSpecUtils`/`MassSpecTools`:
<img width="998" alt="WCM0105" src="https://user-images.githubusercontent.com/5506112/61279873-3c0f4c00-a7b7-11e9-8ff7-73e30b17f975.png">

**Comment by lgatto** [comment]
Both are absolutely excellent. I'll want to stick with my name choice however and favour the 2nd one.

**Comment by jorainer** [comment]
I'd also go for the second (the *core* does not make that much sense...).

Regarding name, I'm fine with `MassSpecUtils`, or alternatively `MsCoreUtils`? I'd prefer `MassSpec` over `Ms`, but `MassSpecCoreUtils` is just too long.

**Comment by lgatto** [comment]
Yes, I agree that `MassSpecCoreUtils` is a bit of a mouthful. Either of `MassSpecUtils` or `MsCoreUtils` are better options. (I like the second one.)

**Comment by jorainer** [comment]
The advantage of `MsCoreUtils` is that it seems to be a unique name - there is no other software tool called that way (while there are plenty `msutils` around). So, if @sgibb agrees we could go for `MsCoreUtils`.

**Comment by sgibb** [comment]
Here we go: https://github.com/rformassspectrometry/MsCoreUtils
