### ISSUE TITLE
RforMassSpectrometry development call - date TBD

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/RforMassSpectrometry#30]
Tentative agenda

- Serialisation of `Spectra` objects
- Error handling when parsing data (see #29)
- Updates on the `MsFeatures` package. Need also to plan a call with more stakeholders in this. 

@sgibb @jorainer - do add topics to be discussed for the next call.

**Comment by jorainer** [comment]
- Status of C-implementations of `join` and `closest` in `MsCoreUtils`.
