### ISSUE TITLE
Package logos 

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/RforMassSpectrometry#31]
The `pkgdown:::find_logo` function checks for default locations for a logo that is used in the pkgdown sites as well as by r-universe. The function looks by default for `logo.svg` of `logo.png` in `.`, `man`, `figures`.

So far, we link to the logo in the [sticker repo](https://github.com/rformassspectrometry/stickers) (for example in the package's README.md files). I think we should add the logo/sticker to the package so it's used in pkgdown and r-universe. 

@jorainer - any preference as to where?

**Comment by jorainer** [comment]
No preference - maybe having it in the main directory would make most sense? I find it confusing to have them in `man` - and we don't have a `figures` directory

**Comment by lgatto** [comment]
Yes, I agree. We seem to converge for `./logo.png` then - thanks!
