### ISSUE TITLE
remove remotes once on Bioc

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/RforMassSpectrometry#5]
Currently, the dependencies point to packages on github. Once these have been submitted to Bioconductor, the remotes should be removed.

**Comment by lshep** [comment]
BiocManager::install  still will only recognize CRAN/Bioconductor -  So the instructions [here](https://rformassspectrometry.github.io/RforMassSpectrometry/articles/RforMassSpectrometry.html#installation) will currently fail as reported on the [support site](https://support.bioconductor.org/p/126872/#126873)  -   temporarily you might want to update the installation page as well and then remove once all are on Bioconductor

**Comment by lgatto** [comment]
Thank you for pointing this out.

**Comment by lgatto** [comment]
@lshep - actually, I think that 
```
BiocManager::install("RforMassSpectrometry/RforMassSpectrometry")
``` 
works. It failed before because of a missing remote, but since this is fixed, I can install all the R for Mass Spectrometry packages in one go.
